apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-java
  labels:
    app: movies-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-java
  template:
    metadata:
      name: movies-java
      labels:
        app: movies-java
      annotations:
        admission.datakit/java-profiler.version: "0.4.0"
    spec:
      securityContext:
        seccompProfile:
          type: Unconfined
      containers:
        - name: movies-java
          image: zhangyicloud/movies-java:centos7
          securityContext:
            seccompProfile:
              type: Unconfined
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_OPTS
              value: ""

      restartPolicy: Always