FROM eclipse-temurin:8u392-b08-jdk

COPY . /opt/java
WORKDIR /opt/java
RUN ./gradlew --no-daemon installDist
ENV JAVA_OPTS "-javaagent:dd-java-agent.jar -XX:FlightRecorderOptions=stackdepth=512"
ENV DD_AGENT_HOST datakit-service.datakit.svc
ENV DD_TRACE_AGENT_PORT 9529
ENV DD_SERVICE ddtrace_java_profiling
ENV DD_VERSION v1.1.2
ENV DD_ENV testing
ENV DD_PROFILING_ENABLED true
ENV DD_PROFILING_ALLOCATION_ENABLED true
ENV DD_PROFILING_DDPROF_ENABLED true
ENV DD_PROFILING_DDPROF_CPU_ENABLED true
ENV DD_PROFILING_DDPROF_WALL_ENABLED true
ENV DD_PROFILING_DDPROF_ALLOC_ENABLED true
ENV DD_PROFILING_DDPROF_LIVEHEAP_ENABLED true
ENV DD_PROFILING_DDPROF_MEMLEAK_ENABLED true

ENV PYROSCOPE_APPLICATION_NAME "java-pyro-demo"
ENV PYROSCOPE_SERVER_ADDRESS http://localhost:4040
ENV PYROSCOPE_FORMAT jfr
ENV PYROSCOPE_PROFILING_INTERVAL 10ms
ENV PYROSCOPE_PROFILER_EVENT=itimer
ENV PYROSCOPE_PROFILER_LOCK 10ms
ENV PYROSCOPE_PROFILER_ALLOC 32k



CMD ./build/install/java-profiling-demo/bin/java-profiling-demo
