apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-java
  labels:
    app: movies-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-java
  template:
    metadata:
      name: movies-java
      labels:
        app: movies-java
      annotations:
        admission.datakit/java-profiler.version: "0.4.1"
    spec:
      containers:
        - name: movies-java
          #image: zhangyicloud/movies-java:centos7
          #image: zhangyicloud/movies-java:centos7-jdk8u172
          image: registry.cn-hangzhou.aliyuncs.com/zhangyicloud/movies-java:uos.20
            #image: zhangyicloud/movies-java:0.3.0-alpine
          securityContext:
            seccompProfile:
              type: Unconfined
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_OPTS
              value: ""

      restartPolicy: Always